- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/home/show.html.erb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20160914194618_create_users.rb
- db/schema.rb
- spec/features/guest_can_create_account_spec.rb
- spec/features/visitor_can_see_all_items_spec.rb
@calaway This is the card that Nate and I worked on. Can you look over it and let me know what you think and merge to dev branch if it looks good?
> 914 bfp create new user

- spec/support/factories.rb
This creates a factory for users with a fixed name and password and a sequentially generated username.
> Factory for users

- app/controllers/sessions_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- spec/features/authenticated_user_can_log_in_spec.rb
> Pass test: authenticated user can log in

- app/controllers/sessions_controller.rb
- spec/features/logged_in_user_can_log_out_spec.rb
All tests are green. This completes the user story authenticated_user_can_log_in
> Complete functionality for user story: authenticated_user_can_log_in

- Gemfile
- Gemfile.lock
- app/controllers/sessions_controller.rb
- spec/features/logged_in_user_can_log_out_spec.rb
Added better_errors gem functionality to project.
> 914 cc better errors

- Gemfile
- Gemfile.lock
- app/controllers/sessions_controller.rb
- spec/features/logged_in_user_can_log_out_spec.rb
- spec/rails_helper.rb
I tested this in byebug and rails console and it's printing awesomely!
> Add awesome_print gem functionality

- app/views/cart/show.html.erb
- spec/features/guest_can_items_to_cart_spec.rb
@calaway here is the thest from @NateAnderson1780 and myself for a guest user adding items to a cart and creating a new account. Can you look over it and let me know if you see anything we missed.
> add user flow for guest adding items to cart and creating new account.

- app/controllers/orders_controller.rb
- app/controllers/sessions_controller.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/orders/index.html.erb
- config/routes.rb
- db/migrate/20160914233936_create_order.rb
- db/migrate/20160914234246_create_order_items.rb
- db/schema.rb
- spec/features/user_can_view_their_orders_spec.rb
- spec/support/factories.rb
Create model, controller, and migration for orders, as well as relationships to items and users. Create user flow to view all previous orders for a user.
> Pass test to view past orders

- app/controllers/cart_controller.rb
- app/models/cart.rb
- app/views/cart/show.html.erb
- config/routes.rb
- spec/features/user_can_adjust_order_number_spec.rb
- spec/models/cart_spec.rb
@calaway @NateAnderson1780. Here is the functionality for updating cart. Can you double check and merge?
> user and change item quantity in cart.

- app/controllers/admin/dashboard_controller.rb
- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/admin/dashboard/index.html.erb
- app/views/sessions/new.html.erb
- config/routes.rb
- db/migrate/20160916133223_add_role_to_users.rb
- db/schema.rb
- spec/features/admin/admin_login_spec.rb
@calaway @brendandillon @NateAnderson1780 this push allows admins to log in and see the dashboard. can someone merge to dev if all looks good? All tests passing.
> 916 bfp admin login

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/order_item.rb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- config/routes.rb
- spec/features/user_can_view_their_orders_spec.rb
- spec/features/visitor_can_remove_items_from_cart_spec.rb
- spec/support/factories.rb
Looks like this might have a merge conflict. I'll dig into it and see if I can resolve it.
> 915 cc viewing a past order

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css
- app/assets/stylesheets/application.css.sass
- app/views/cart/show.html.erb
- app/views/categories/show.html.erb
- app/views/items/index.html.erb
- app/views/layouts/application.html.erb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
This commit adds bootstrap and basic styling to our views
> 917 bd style_party

- app/controllers/errors_controller.rb
- app/controllers/users_controller.rb
- config/application.rb
- config/routes.rb
- spec/features/visitor/vistor_cannot_sees_user_info_spec.rb
Here is the test/implementation so a visitor cannot view user pages or admin things. 
@calaway @brendandillon @NateAnderson1780
> 916 bfp visitor cant see user info

- Gemfile
- app/controllers/orders_controller.rb
- spec/features/admin/admin_order_status_spec.rb
- spec/features/user/user_can_not_add_retired_items_to_cart_spec.rb
- spec/features/visitor/visitor_can_register_and_check_out_with_items_in_cart_spec.rb
- spec/features/visitor/visitor_can_see_items_in_cart_after_creating_account_spec.rb
Went through all files and tried to make rubocop play nice with them. Please merge when checked. 
@calaway @brendandillon @NateAnderson1780
> cleaned up rubocop complaints.

- app/controllers/admin/dashboard_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/admin/dashboard/index.html.erb
- config/routes.rb
- spec/features/admin/admin_order_status_spec.rb
- spec/models/order_spec.rb
This branch creates an admin dashboard page in which they are able to view, sort, and update orders. It also adds the functionality for orders to be updated.
> 917 bd admin orders

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
- spec/features/visitor/visitor_can_see_one_item_spec.rb
This branch adds a show page for individual items with formatting, as well as a new feature test to ensure that this show page can be accessed and has the requisite content.
> Add item show page

- app/controllers/orders_controller.rb
- app/models/checkout.rb
- app/views/items/index.html.erb
- spec/features/visitor/visitor_can_register_and_check_out_with_items_in_cart_spec.rb
- spec/support/factories.rb
Checkout is now loading the order and order items
> 918 cc checkout transaction

- Gemfile
- app/controllers/admin/base_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- db/seeds.rb
Added the functionality that Sal wanted (that the 404 page NOT render anything from layout). 
Can you merge if all looks good?
@calaway @brendandillon @NateAnderson1780
> 919 bfp layout false

- Gemfile
- app/controllers/admin/base_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/views/orders/show.html.erb
- db/seeds.rb
fix the error that was showing params in order show page. Can you merge if it looks good. 
@calaway @brendandillon @NateAnderson1780
> 919 bfp fix order page

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/cart_controller.rb
- app/controllers/users_controller.rb
- app/models/checkout.rb
- app/models/message_sender.rb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
- db/migrate/20160920155435_add_phone_number_to_users.rb
- db/schema.rb
- spec/features/visitor/visitor_can_register_and_check_out_with_items_in_cart_spec.rb
SMS order confirmaiton is fully functional
> 919 cc sms order confirmation

- app/controllers/errors_controller.rb
- config/routes.rb
Took out a few directories that were not being used. 
@NateAnderson1780 can you check and merge if its good?
> cleaned up useless directories.

- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- spec/features/user/user_can_edit_their_information_spec.rb
@calaway @bfpepper @brendandillon Test error is fixed. Only one error on rspec related to Twilio. Should be fixed upon merging.
> fixed form for user and added bad path test for user edits info

- app/controllers/admin/items_controller.rb
- spec/features/admin/admin_can_create_items_spec.rb
@calaway @bfpepper @brendandillon final sad path test created for admin items controller. Should be good to merge. All tests passing.
> 921_na_sad_paths

- app/assets/stylesheets/custom_styles.css
- app/models/cart.rb
This fixes the negative item bug and also improves the formatting of item thumbnails.
> 921 bd we are not a pawn shop

- app/assets/stylesheets/custom_styles.css
- app/controllers/home_controller.rb
- app/models/cart.rb
- app/views/application/_carousel.html.erb
- app/views/home/show.html.erb
> built and styled home page
